# 2.1.7. Получение детальной информации по товару
GET http://localhost:5000/offers/65508a19a106825f8c621708 HTTP/1.1+
Content-Type: application/json

###

## 2.1.6. Получение списка товаров. TODO Применения фильтров в запросе.
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###

## 5.1.1. Сервис предоставляет ресурс для создания новых карточек товаров.
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###

## 2.1.5. Удаление товара.

DELETE http://localhost:5000/offers/6553aab20e67e0a900012370 HTTP/1.1
Content-Type: application/json

###

## 2.1.4. Редактирование карточки товара.

PATCH http://localhost:5000/offers/655117d18e0f26f8c21686d2 HTTP/1.1
Content-Type: application/json

{
  "title": "Kasapoglu Apart",
  "description": "Kasapoglu Apart Cleopatra Beach",
  "price": 44444,
  "rating": 2.0
}

###
